// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileConverter() {
  return window['go']['main']['App']['FileConverter']();
}

export function GetOutDir() {
  return window['go']['main']['App']['GetOutDir']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetOutDir() {
  return window['go']['main']['App']['SetOutDir']();
}
