// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {http} from '../models';

export function FileConverterDialog():Promise<string>;

export function FileConverterRoute(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;

export function GetOutDir():Promise<string>;

export function SetOutDir():Promise<string>;
