// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileConverter():Promise<string>;

export function GetOutDir():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SetOutDir():Promise<string>;
