// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileConverterDialog() {
  return window['go']['main']['App']['FileConverterDialog']();
}

export function FileConverterRoute(arg1, arg2) {
  return window['go']['main']['App']['FileConverterRoute'](arg1, arg2);
}

export function GetOutDir() {
  return window['go']['main']['App']['GetOutDir']();
}

export function SetOutDir() {
  return window['go']['main']['App']['SetOutDir']();
}
